@echo off
echo Starting Playto Payout Engine...

echo Starting Celery Worker...
start cmd /k "cd backend && .\venv\Scripts\activate.bat && celery -A config worker --loglevel=info --pool=solo"

echo Starting Celery Beat...
start cmd /k "cd backend && .\venv\Scripts\activate.bat && celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"

echo Starting Frontend...
start cmd /k "cd frontend && npm install && npm run dev"
